
version: "3.9"

services:
  go-aws-ec2:
    container_name: go-aws-ec2
    build: .
    ports:
      - "10000:10000"
    restart: on-failure

  prometheus:
    build:
      context: ./tools/prometheus
      dockerfile: Dockerfile
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.level=warn
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.page-title=Go AWS EC2
    ports:
      - "9090:9090"
